name: hs_workflow_intro_to_github_action
on: [push]

jobs:
  shows-secret-phrase:
    runs-on: ubuntu-latests
    steps: 
      - uses: action/checkout@v3
        with:
          repository: abystoma/test
          ref: main
      - name: Show me the answer
        run: cat answer.txt
